grupo: "Academia"

aplicacion:
  version: 1.0
  pais: "mx"
  lenguaje: "es-mx"
  user: "Rolando"

eureka:
  client:
    seriveUrl:
      defaultZone: http://localhost:8761/eureka/
    healtcheck:
      enable: false
    