grupo: "Academia"

aplicacion:
  version: 1.0
  pais: "mx"
  lenguaje: "es-mx"
  user: "Rolando"

eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-3-144-104-148.us-east-2.compute.amazonaws.com:8761/eureka/
    healthcheck:
      enable: true